# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(verbose_name='Température')),
                ('vib', models.FloatField(verbose_name='Vibrations')),
            ],
        ),
    ]
