# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpanel1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydatas',
            name='vib',
        ),
        migrations.AddField(
            model_name='mydatas',
            name='vib1',
            field=models.FloatField(default=0.0, verbose_name='Vibrations'),
        ),
        migrations.AddField(
            model_name='mydatas',
            name='vib2',
            field=models.FloatField(default=0.0, verbose_name='Vibrations2'),
        ),
        migrations.AlterField(
            model_name='mydatas',
            name='temp',
            field=models.FloatField(default=0.0, verbose_name='Température'),
        ),
    ]
