# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpanel1', '0002_auto_20170510_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydatas',
            name='temp',
        ),
    ]
